### ISSUE TITLE
1.20.1 version

### ISSUE THREAD

**Issue by benio1394** [willatendo/End-Of-Minecraft#1]
Sorry if this request is annoying, but I want to suggest support for 1.20.1 version, as it s main modding version and have a few mods that could work pretty well with concept of wasteland. It's a big opportunity to create pretty intresting apocalypse modpack for fabric. I honestly missed mod like yours, so thank you for your work.

**Comment by willatendo** [comment]
I'm sorry, but I don't downport my mods. I understand it's annoying to have mods you want to use on separate versions (I've been there _many_ times) but I don't enough time to run multiple versions. I hope they update soon so you can create a modpack and thanks for the compliment!
